services:
  api:
    build: .
    container_name: taskflow-api-container
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: taskflow-redis
    ports:
      - "6379:6379"